.mypy.ini
.pre-commit-config.yaml
poetry.lock
pyproject.toml

Move mypy config to pyproject.toml; Fix autoformatting in pre-commit

---

blackboxopt/base.py
pyproject.toml
tests/base_test.py

Make invalid objectives exception message more expressive

---

blackboxopt/visualizations/visualizer.py
pyproject.toml
tests/visualization_test.py

This is only a quickfix. (already started on refactoring the visualization).

Fix objectives matrix visualization; Add infos for pypi.org

---

.github/workflows/python.yaml
README.md
mkdocs.yml
poetry.lock
pyproject.toml

See result at [boschresearch.github.io/blackboxopt](https://boschresearch.github.io/blackboxopt/).

Publish docs to gh pages

---

.github/workflows/python.yaml

Use different placeholder mail address

---

blackboxopt/__init__.py
blackboxopt/base.py
blackboxopt/optimization_loops/utils.py
pyproject.toml
tests/base_test.py

Generic raise on unknown or incomplete

---

blackboxopt/__init__.py
blackboxopt/base.py
blackboxopt/evaluation.py
blackboxopt/examples/dask_distributed.py
blackboxopt/optimization_loops/testing.py
blackboxopt/optimization_loops/utils.py
blackboxopt/optimizers/testing.py
pyproject.toml
tests/evaluation_test.py
tests/optimization_loops/dask_distributed_test.py
tests/optimizers/bohb_test.py
tests/optimizers/hyperband_test.py
tests/optimizers/staged/bohb_test.py
tests/optimizers/staged/iteration_test.py

Signed-off-by: Grossberger Lukas <Lukas.Grossberger@de.bosch.com>

add context and constraints as optional to evaluation

---

blackboxopt/__init__.py

Expose EvaluationsError and ContextError in init for consistency

---

blackboxopt/evaluation.py
pyproject.toml
tests/evaluation_test.py

Support context in evaluation get specification

---

.github/workflows/python.yaml
pyproject.toml

Fix docs deployment

---

blackboxopt/visualizations/visualizer.py
pyproject.toml

I propose this as a start to also refactor the other visualizations into more concise and dataframe-driven structure.
What do you think?

Refactor multi objective visualization

---

blackboxopt/visualizations/to_html_patch.js
blackboxopt/visualizations/utils.py
blackboxopt/visualizations/visualizer.py
pyproject.toml

Adds functionality to the html version of the visualization:
- Click on data point to toggle persistence of hover-box
- Click on text-line in hover-box to copy the value of the line into clipboard.

Inject additional js in html output of to_html()

---

blackboxopt/visualizations/visualizer.py
pyproject.toml

Import to_html with full module path; Bump version

---

blackboxopt/optimization_loops/dask_distributed.py
blackboxopt/optimization_loops/sequential.py
blackboxopt/optimization_loops/testing.py
blackboxopt/optimization_loops/utils.py
poetry.lock
pyproject.toml
tests/optimization_loops/dask_distributed_test.py
tests/optimization_loops/sequential_test.py

add opt out of auto handling exceptions in optimization loops

---

blackboxopt/visualizations/utils.py
blackboxopt/visualizations/visualizer.py
pyproject.toml
tests/visualization_test.py

Given that we require an objective in the `Visualizer` now, this is breaking and would warrant another major version bump. What do you think @dynobo?

Feature/objectives in visualizer (#28)

---

blackboxopt/optimization_loops/utils.py

Clarify logging message about end of evaluation

---

blackboxopt/optimization_loops/sequential.py
pyproject.toml

this now produces, e.g.
```
2022-01-13 15:26:32,065 - bbo - INFO - The optimizer proposed a specification for evaluation:
{
"configuration": {
"x": 0.7652686018123811
},
"settings": {
"fidelity": 1.0
},
"optimizer_info": {
"model_based_pick": true,
"configuration_key": [
8,
0,
0
],
"id": "c0fa7406-7bca-41a5-80aa-5bbf5c65ac8c"
},
"created_unixtime": 1642083992.064288,
"context": null
}
2022-01-13 15:26:32,068 - bbo - INFO - Reporting the result from the evaluation function to the optimizer:
{
"objectives": {
"score": -0.0550988292951145
},
"configuration": {
"x": 0.7652686018123811
},
"settings": {
"fidelity": 1.0
},
"optimizer_info": {
"model_based_pick": true,
"configuration_key": [
8,
0,
0
],
"id": "c0fa7406-7bca-41a5-80aa-5bbf5c65ac8c"
},
"created_unixtime": 1642083992.064288, …
```

change log level from sequential optimization loop to info and pretty print

---

blackboxopt/utils.py
blackboxopt/visualizations/visualizer.py
pyproject.toml
tests/visualization_test.py

The pareto front visualization was faulty when used with objective values where greater is better.

make multi objective visualization objective direction aware

---

blackboxopt/utils.py
pyproject.toml
tests/utils_test.py

add option to override none replacement value in get loss vector util

---

blackboxopt/optimization_loops/sequential.py
pyproject.toml
tests/optimization_loops/sequential_test.py

add post evaluation callback to sequential optimization loop

---

blackboxopt/visualizations/visualizer.py
pyproject.toml

Use correct argument for mapping colors to values

---

blackboxopt/optimizers/space_filling.py
poetry.lock
pyproject.toml
tests/optimizers/space_filling_test.py

This PR introduces a SciPy Sobol sequence based "optimizer".

add space filling sobol sequence based optimizer

---

.github/workflows/python.yaml
poetry.lock
pyproject.toml

add support for Python 3.10

---

poetry.lock
pyproject.toml

Increase pytest version to solve dependabot finding

---

blackboxopt/__init__.py
blackboxopt/optimizers/testing.py
pyproject.toml

Add constraints values while reporting evaluations to be able to test constraints aware optimizers. 
Signed-off-by: anna.eivazi <anna.eivazi@de.bosch.com>

Add constraints

---

blackboxopt/__init__.py
blackboxopt/optimizers/botorch_base.py
pyproject.toml

Opening this as a draft just so we don't forget to fix this but let's also investigate why it didn't trip any tests and linting rules. Who ever gets to it first, @dynobo, or together :relaxed:

fix missing evaluation sorting in botorch base

---

blackboxopt/utils.py
tests/utils_test.py

add utils to save and load a study pickle

---

.github/workflows/python.yaml

_Should_ fix #115, but it can only be verified once merged to `main`.

Run reporting step also on main
