- .github/workflows/python.yaml
- poetry.lock
- pyproject.toml
Adds [pydocstyle](https://github.com/PyCQA/pydocstyle) for linting google-styled docs. Check is added to gh action, but with the "continue-on-error" switch, as we have to fix quite a bunch of issues first (and/or adjust the linter config).
Hints:
- Contributors using `vscode` can easily enable issue-highlighting by enabling `python.linting.pydocstyleEnabled` in the settings UI.
- In CLI just run `pydocstyle` (or `pydocstyle --explain` for more details)
> Add pydocstyle linter

- blackboxopt/base.py
- blackboxopt/optimization_loops/dask_distributed.py
- blackboxopt/optimization_loops/sequential.py
- blackboxopt/optimizers/staged/optimizer.py
- blackboxopt/optimizers/testing.py
- blackboxopt/utils.py
- poetry.lock
- pyproject.toml
- tests/optimizers/bohb_test.py
- tests/optimizers/hyperband_test.py
- tests/optimizers/staged/bohb_test.py
This PR switches from reporting evaluations individually to allow reporting batches (lists) of evaluations, as discussed with @LGro in person. 
- Allows better performance in cases where we can fit a model with all evaluations in one run instead fitting it multiple times for every individual evaluation. @sfalkner : Would this be the case for e.g. BOHB? If yes, feel free to contribute an PR. :slightly_smiling_face:
- The `StagedIterationOptimizer` and the `sequential` optimization loop are not (yet?) adopted to leverage this functionality and just keep processing the evaluations individually.
- Individual evaluations still can be reported as a list of one item. (I propose to not allow `Union[List[Evaluation], Evaluation]` to keep the code and tests etc. more simple. What do you think?) …
> Switch to report evaluations in batches

- blackboxopt/evaluation.py
- pyproject.toml
Creates compatibility with `datetime` powered timestamp conversion, which creates six instead of seven decimal places for unix timestamps compared to `time.time()` and would thus cause equality checks to fail after conversion.
> replace time with datetime for unix timestamps

- blackboxopt/base.py
- blackboxopt/optimization_loops/dask_distributed.py
- blackboxopt/optimization_loops/sequential.py
- blackboxopt/optimization_loops/testing.py
- blackboxopt/optimizers/random_search.py
- blackboxopt/optimizers/staged/iteration.py
- blackboxopt/optimizers/staged/optimizer.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
- tests/optimization_loops/dask_distributed_test.py
- tests/optimizers/bohb_test.py
- tests/optimizers/hyperband_test.py
- tests/optimizers/random_search_test.py
- tests/optimizers/staged/bohb_test.py
- tests/optimizers/staged/iteration_test.py
For UX reasons, it makes sense to change away from `get_`, but instead of the now introduced `create_` we could also go for `propose_` if you prefer that, @sfalkner / @dynobo.
> rename get_evaluation_specification to create_evaluation_specification

- blackboxopt/optimizers/staged/bohb.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
- tests/optimizers/staged/bohb_test.py
- added ordinal variables to BOHB
- changed representation of categorical values to match the statsmodels KDEs expectation of ints
- added tests and docstring
Signed-off-by: Falkner Stefan (CR/PJ-AI-R32) <Stefan.Falkner@de.bosch.com>
> BOHB can handle ordinal variables now

- poetry.lock
- pyproject.toml
`statsmodels` below 0.13.x throw an error while running on scipy above 1.8.0. The latest version of `statsmodels` addresses the issue.
Signed-off-by: Anna Eivazi <anna.eivazi@de.bosch.com>
> Use latest version of statsmodels that will work with latest scipy

- blackboxopt/visualizations/utils.py
- pyproject.toml
- tests/visualization_test.py
We had the issue where points were considered pareto efficient when they were "on the pareto front" despite not being on a corner of the pareto front. This PR extends the test with two cases that failed before and are fixed now with what is hopefully also a more readable despite somewhat more complex implementation.
> fix mask pareto efficient visualization util

- .github/workflows/python.yaml
- pyproject.toml
Given that we promise to support different Python versions, let's test that we actually do.
To that end this PR separates linting from testing and introduces a test matrix with Python versions 3.7, 3.8, and 3.9. We also explicitly exclude the yet unsupported 3.10 now in the pyproject.toml
FYI: @attilareiss and @sfalkner 
> test on all supported python versions

- .github/workflows/python.yaml
- poetry.lock
- pyproject.toml
This PR addresses CVE-2021-34141 by updating the numpy version lower bound to 1.22.0 and notably also with that requires a lower version bound increase on the compatible Python version to 3.8 (keep in mind the downstream effects).
> bump numpy lower bound to address CVE-2021-34141

- blackboxopt/__init__.py
- blackboxopt/visualizations/visualizer.py
- pyproject.toml
- tests/visualization_test.py
Did that during my train ride as one way to introspect the evaluation results in a higher dimensional search space with a [parallel coordinates plot](https://plotly.com/python/parallel-coordinates-plot/).
Unfortunately, I can't upload an image here (proxy?), but you can debug into the the unit test and and do a `fig.show()` there, which also gives a better impression about the interactivity.
Known issues we might want to tackle in the future:
- Ordering of ordinal parameter values is not ensured
- Axis of Integer parameters might still show axis ticks on fractional positions
> Add parallel coordinates plot

- blackboxopt/__init__.py
- blackboxopt/optimization_loops/dask_distributed.py
- pyproject.toml
This PR adds DEBUG level logging of evaluations to the dask distributed optimization loop and refactors the naming and return statement of `check_for_results` a bit for clarity.
> add debug logging evaluations in dask loop

- blackboxopt/__init__.py
- blackboxopt/visualizations/visualizer.py
- pyproject.toml
- tests/visualization_test.py
I notice that issue, when I tried to visualize the run with a parameterspace containing:
```python
ps.CategoricalParameter("p1", (None, [0,1,2], [3,2,4]))
```
While this also can be avoided on user side by choosing tuples instead of list, the proposed change of converting to string first makes the visualization robust for such cases without any downsides (I think?).
> Fix parallel coordinate plot breaking in case of non-hashable parameter values

- blackboxopt/__init__.py
- blackboxopt/visualizations/visualizer.py
- pyproject.toml
- tests/visualization_test.py
Before this PR, when visualizing pairwise objective scatter plots with two objectives, we showed the same scatter plot matrix like with more than two objectives even though it is not necessary. This PR now shows a simple scatter plot in the two objectives case to save space and be less confusing visually due to displaying the same plot twice, mirrored, in a matrix diagonal.
> display single scatter plot instead of scatter matrix for two objectives

- blackboxopt/__init__.py
- blackboxopt/utils.py
- blackboxopt/visualizations/utils.py
- pyproject.toml
- tests/utils_test.py
- tests/visualization_test.py
The time has come and we benefit from a function that just takes a list of evaluations and filters out the pareto front, in addition to / building on the previous implementation of the loss matrix based mask.
Signed-off-by: Grossberger Lukas (CR/AIR2.2) <Lukas.Grossberger@de.bosch.com>
> add filter pareto front from eval util

- blackboxopt/__init__.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
- tests/optimizers/random_search_test.py
This PR adds a test to the default compatibility test suite that contains a condition in the search space, i.e. has a hierarchical search space. This change requires all optimizers that test against the default tests to support conditional spaces.
Signed-off-by: Grossberger Lukas (CR/AIR2.2) <Lukas.Grossberger@de.bosch.com>
> add conditional space reference test

- architecture_decision_records/deterministic-sorting-of-evaluations.md
- blackboxopt/utils.py
- tests/utils_test.py
This doesn't introduce any functional changes yet, but prepares fixing determinism issues in #64.
The goal is to provide a function that's able to deterministically sort a `List[Evaluation]` by _only_ considering optimization relevant attributes, disregarding all others that might be subject to change/randomness (e.g. timestamps). 
Sorting the dictionary keys is the only option I found for being robust also against changes in the order of parameters, too. 
Performance depends a lot on the amount of parameters and the number of elements. In a quick test I tried different methods using a list of 1000 evaluations with 20 parameters.  The time is total seconds for sorting 1000 times (or the mean milliseconds per sort):
```
json sorted 
32.07862658100203
md5 of json sorted
29.56752566599971 …
```
> Add utility function to derministically sort list of evaluations

- blackboxopt/__init__.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
Proposal for a test to verify deterministic behavior when reporting a list of evaluations at once (here as initial data), even if the order of the list varies. 
Currently all optimizer pass the test (**EDIT:** except BOHB), but still I'm not 100% sure: is this _always_ the _desired_ behavior? Or are there cases, where we expect and desire different optimizer behavior depending on the order?
> Add additional reference test for determinism

- blackboxopt/__init__.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
Signed-off-by: Anna Eivazi <anna.eivazi@de.bosch.com>
This PR proposes to increase number of configurations (requested sequentially) for checking optimizer determinism, which makes test more reliable and less dependent on number of initial sampling strategies or optimizer's specific heuristics for initial proposals.
> Extend deterministic ref test to compare five configurations.

- blackboxopt/__init__.py
- blackboxopt/optimizers/botorch_base.py
- pyproject.toml
Small addition that allows for models that are not subclasses of ExactGP when using `SingleObjectiveBOTorchOptimizer`
Signed-off-by: Lucia Reeb [lucia.reeb@de.bosch.com](mailto:lucia.reeb@de.bosch.com)
> Reshape fantasized model only for ExactGP

- .github/workflows/python.yaml
- blackboxopt/__init__.py
- poetry.lock
- pyproject.toml
- tests/optimization_loops/dask_distributed_test.py
Currently, `dask.distributed` still seems to struggle with Py3.11 or need special treatment. Thus, opening the support for Python 3.11 as a draft for now.
> add py3.11 to compatible versions and CI/CD test

- .gitignore
- architecture_decision_records/random-seed-for-reference-tests.md
- blackboxopt/__init__.py
- blackboxopt/optimizers/testing.py
- poetry.lock
- pyproject.toml
- tests/optimizers/bohb_test.py
- tests/optimizers/botorch_base_test.py
- tests/optimizers/conftest.py
- tests/optimizers/hyperband_test.py
- tests/optimizers/random_search_test.py
- tests/optimizers/space_filling_test.py
With our recent issues with flaky tests and global seeding, I propose to use a pytest fixture to create a random (but fixed) seed for each of the reference tests.
Benefits:
* Removes all global seeding
* Avoids runing tests with always the same fixed seeds -> will spot problems earlier
* If a test fails, the seed will show up in the log and the test can be reproduced easily
What do you think?
Signed-off-by: Reeb Lucia <Lucia.Reeb@de.bosch.com>
> Remove global seeding and add test fixture for seed

- blackboxopt/__init__.py
- blackboxopt/optimizers/botorch_base.py
- pyproject.toml
- tests/optimizers/botorch_base_test.py
Despite conditioning the model on data when reporting for the GPBO optimizer, we never stored the updated model. Thus, we also missed the lack of support for handling `None` objectives, which is also now there.
> fix model update in gpbo, add nan filtering

- blackboxopt/__init__.py
- blackboxopt/optimizers/botorch_base.py
- pyproject.toml
- tests/optimizers/botorch_base_test.py
When a search space is purely discrete, we randomly sample by default 5k points to evaluate / optimize the acquisition function at, to avoid issues that arise when the acquisition function gets stuck proposing points that can't be evaluated (could happen due to continuous representation via parameterspace).
For mixed spaces the state remains unchanged, so there we might still suffer from the mentioned issue.
> add discrete acquisition function optimization for discrete spaces with gpbo

- blackboxopt/__init__.py
- poetry.lock
- pyproject.toml
This PR allows to use both, the previous parameterspace version as well as the most recent one that now requires parameter names to be valid python variable names, so that we can use them together but nobody is forced to switch yet. We can make this tighter again when we rely on specific new parameterspace features that the older versions don't have.
> add parameterspace versions 0.8.* as compatible

- blackboxopt/__init__.py
- blackboxopt/optimizers/botorch_base.py
- blackboxopt/optimizers/botorch_utils.py
- pyproject.toml
- tests/optimizers/botorch_utils_test.py
Supporting not only one but also multiple objectives in our BOTorch utils function `to_numerical`.
> add support for multiple objectives in botorch to numerical

- blackboxopt/__init__.py
- blackboxopt/optimizers/testing.py
- pyproject.toml
This PR adds valid constraint values to the first evaluation in the reference test `opimize_single_parameter_sequentially_for_n_max_evaluations`. The behavior for the previous value `None` was not defined.
> Fix constraints in reference Test

- blackboxopt/__init__.py
- blackboxopt/utils.py
- pyproject.toml
- tests/utils_test.py
Before, one would need to take care of storing evaluations with the search space they came from and the matching objectives individually. Now, there are two utility functions for saving and loading to and from JSON respectively.
There is also a corresponding follow up at `feature/save-and-load-study-pickle` in case we like this pattern for JSON.
> add utils to save and load a study json

- .github/workflows/python.yaml
This PR aims to resolve the warnings:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> update checkout action v2 -> v3

- poetry.lock
- pyproject.toml
I'd like to propose being less conservative with the version bound of our own package parameterspace to avoid having to adjust the upper bound regularly.
> remove upper version bound for parameterspace dependency

- .github/workflows/python.yaml
- blackboxopt/__init__.py
- pyproject.toml
It seems like creating releases (and with that a tag) via the GitHub web ui doesn't trigger our CI/CD pipeline anymore. This PR should fix that.
> add on release published as ci/cd trigger

- .github/workflows/python.yaml
- blackboxopt/__init__.py
Seems like failing tests didn't cause our GH Actions workflow to fail anymore ever since I added the pipe for the coverage report (see two commits in this PR).
> add pipefail for tests in action (closes #111)

- .github/workflows/python.yaml
- poetry.lock
- pyproject.toml
Our self made coverage reporting wasn't only causing failing tests to slip (#111) but also hid the errors when they occurred. So here is an attempt to switch to https://github.com/marketplace/actions/python-coverage-comment as recommended by @dynobo.
> replace custom coverage action with py-cov-comment

- blackboxopt/optimization_loops/sequential.py
- tests/optimization_loops/sequential_test.py
* Close #97 by casting the `user_info` to string before dumping it to JSON for logging
* Add pre-evaluation callback
* Add reference to evaluation function wrapper in docstring for more transparency about `catch_exceptions_from_evaluation_function` argument
> add pre eval callback and stringify user info for logging

- blackboxopt/optimizers/botorch_base.py
- blackboxopt/optimizers/botorch_utils.py
- tests/optimizers/botorch_base_test.py
Moving the `predict_model_based_best` method logic into a pure function, leaving the method as a user facing wrapper for convenience. This is in preparation for the upcoming botorch base refactoring to enable multi objective optimizers more easily.
> refactor botorch base predict_model_based_best into function

- blackboxopt/__init__.py
- blackboxopt/visualizations/visualizer.py
- poetry.lock
- pyproject.toml
While it's nice that we can just re-use pymoos hypervolume implementation, this introduces a rather specific optimization related dependency for our visualization extra. To allow for compatibility with a wider range of pymoo versions, courtesy of pymoo's diligence regarding backward compatibility, this PR switches to an older (hypervolume) indicator api that is still supported and thus allows compatibility with pymoo 0.5 as well as the most recent 0.6.
> relax pymoo bound to 0.5 using backward compat hypervolume api

- docs/index.md
Whenever I speak with folks using BOHB or Hyperband, they struggle to grasp the connection between the fidelity related settings and how they translate to the actual fidelity levels that are evaluated. This little JavaScript calculator in our docs should help with that, I hope.
I was contemplating whether to go for a table or flexbox with div containers, and concluded that the form is so small, that mobile device optimization is not necessary, wdyt?
> add fidelities calculator for staged iteration optimizers

- CONTRIBUTING.md
- README.md
- blackboxopt/__init__.py
- docs/index.md
- docs/optimization-loops/dask-distributed.md
- docs/optimization-loops/overview.md
- docs/optimization-loops/sequential.md
- docs/optimization-loops/testing.md
- docs/optimizers/bohb.md
- docs/optimizers/botorch.md
- docs/optimizers/space-filling.md
- docs/optimizers/testing.md
- mkdocs.yml
- pyproject.toml
To help newcomers find their way around `blackboxopt`, this PR adds explicit docs pages for the most important optimizers and optimization loop implementations.
> add basic docs for optimizers and loops

- .github/workflows/python.yaml
This should fix the actions error we saw in our previous release: https://github.com/boschresearch/blackboxopt/actions/runs/7916729063
> update actions to avoid coverage report on release

- blackboxopt/__init__.py
- blackboxopt/optimizers/botorch_base.py
- blackboxopt/optimizers/botorch_utils.py
- poetry.lock
- pyproject.toml
- tests/optimizers/botorch_base_test.py
Higher versions of botorch change some minor defaults and import APIs, breaking the current code. This PR addresses this issue and ensure compatibility with botorch versions between 0.7.x up to, and including, 0.14.x (=latest).
> Ensure compatibility with 0.14>=botorch>0.7
